# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Sun 25 May 2025 10:40:39 AEST

name: Random Push Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.26.4
        pip install lxml
        pip install --upgrade pandas_ta
        pip install flake8 pytest
        pip install pandas yfinance
        pip install gspread
        pip install --upgrade google-auth
        pip install pypnf
        pip install google-api-python-client
        pip install SciPy
 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run when pushed
      run: |
        python sso.py
      env:
        TOKEN: ${{ secrets.TOKEN}}
